import { ArrowRight, Check, LoaderCircle, LockKeyhole, Mail } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import Navbar from '../components/Navbar';
import { api } from '../services/api';

export default function Register() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ email: '', password: '', confirm: '' });
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setError(''); if (!form.email || !form.password || !form.confirm) return setError('Complete all fields to create your account.'); if (form.password.length < 6) return setError('Password must be at least 6 characters.'); if (form.password !== form.confirm) return setError('Passwords do not match.'); setLoading(true); try { const data = await api.register(form.email, form.password); if (data?.message) throw new Error(data.message); navigate('/login', { state: { registered: true } }); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <div className="min-h-screen bg-ink text-white"><Navbar /><main className="mx-auto flex max-w-md px-5 py-12 sm:py-20"><div className="w-full animate-rise"><div className="mb-8"><div className="icon-badge"><Check size={20} /></div><h1 className="mt-6 font-display text-3xl font-bold">Create your account</h1><p className="mt-2 text-slate-400">Start making every link count.</p></div><form onSubmit={submit} className="space-y-5"><label className="field-label">Email<input className="field" type="email" autoComplete="email" placeholder="you@example.com" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><Mail className="field-icon" size={17} /></label><label className="field-label">Password<input className="field" type="password" autoComplete="new-password" placeholder="At least 6 characters" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><LockKeyhole className="field-icon" size={17} /></label><label className="field-label">Confirm password<input className="field" type="password" autoComplete="new-password" placeholder="Repeat your password" value={form.confirm} onChange={e => setForm({ ...form, confirm: e.target.value })} /><LockKeyhole className="field-icon" size={17} /></label>{error && <p className="error-box">{error}</p>}<button className="button-primary w-full py-3.5" disabled={loading}>{loading ? <LoaderCircle className="animate-spin" size={18} /> : <ArrowRight size={18} />} {loading ? 'Creating account...' : 'Create account'}</button></form><p className="mt-8 text-center text-sm text-slate-400">Already have an account? <Link className="font-semibold text-electric hover:text-white" to="/login">Sign in</Link></p></div></main></div>;
}